language: node_js
node_js:
  - node
  - 8
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run lint
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release